#!/usr/bin/env bash
# display the content of the file /etc/passwd and display username, user id and home directory path for the user

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd" 
