#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Displays the IP and HTTP status code.

awk '{print $1 " " $9}' apache-access.log

Footer

© 2023 GitHub, Inc.

Footer navigation

Terms

Privacy

Security

Status

Docs

C
