#!/usr/bin/env bash
# display numbers from 1 to 20, for the line 4th display "bad luck from china", at 9th line "bad luch from japan", at 17th line "bad luck from italy"

i=1

while [ $i -le 20 ]
do
      echo "$i"
      case $i in
           "4") echo "bad luck from China";;
           "9") echo "bad luck from Japan";;
           "17") echo "bad luck from Italy";;
       esac
        (( i++ ))
done         
