#!/usr/bin/env bash
# The script creates a file, displays To infinity and beyond indefinitely.
# Dipslay the  hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# deletes the file and terminates itself when reciving SIGQUIT or SIGTERM signal

function terminator() {
    rm /var/run/myscript.pid
    exit
}

trap "echo I hate the kill command;terminator" SIGTERM
trap "echo Y U no love me?!;terminator" SIGINT

echo $$ >> /var/run/myscript.pid

while true 
do
	echo 'To infinity and beyond';
done
